(() => {
  const harder = document.body.dataset.frankensteinLevel === "harder";
  const key = `mye-frankenstein-${harder ? "harder" : "easier"}-v1`;
  const commonBefore = [
    ["scientist", harder ? "The __________ carefully recorded the results of each experiment to cure the disease." : "The __________ registered the results of the experiment.", ["ship captain", "lawyer", "scientist", "economist"], 2, "Would you like to be a scientist?"],
    ["monster", "The criminal was called a(n) ________ for his terrible actions.", ["corpse", "angel", "monster", "statue"], 2, harder ? "Can you mention any monsters? What about people you consider monsters?" : "Can you mention any famous monsters?"],
    ["sister", harder ? "Your __________ can be your spouse's sister or your brother's wife." : "Your __________ can be your partner's sister or your brother's wife.", ["mother-in-law", "brother-in-law", "sister-in-law", "niece"], 2, "Do you have a sister-in-law?"],
    ["tale", "My grandmother told me a _______ about an old man and a wolf.", ["tall", "tail", "tale", "trail"], 2, "Do you have a favorite tale?"],
    ["life", harder ? "The doctors worked quickly because it was a _________ situation." : "The doctors worked fast because it was a _________ situation.", ["alive and dead", "death and live", "life and death", "live and died"], 2, harder ? "Is death a problem?" : "Are you afraid of death?"],
    ["ego", harder ? "Egotistical describes..." : "An egotistical person is...", harder ? ["someone who can teach others easily.", "someone who is more patient and calm than others.", "someone who believes they are more important and better than others.", "people who resort to violence whenever someone disagrees with them."] : ["someone who is a good teacher.", "someone who is very patient and calm.", "someone who thinks they are more important than others.", "people who are violent when someone has a different opinion."], 2, "Do you know anybody like that?"]
  ];
  const plot = harder
    ? ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["A brilliant scientist conducts a monstrous experiment to bring one man back to life through electricity and animal body parts.", "A brilliant scientist brings a creature to life in a monstrous experiment that ultimately leads to the undoing of both creator and creation.", "An average scientist brings a monster to life in an experiment involving his brother and wife."], 1, "Get ready for a uniquely profound movie experience."]
    : ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["A brilliant scientist brings one man back to life using electricity and animal body parts.", "A brilliant scientist creates a monster in a crazy experiment that affects both the creator and his creation.", "A common scientist creates a monster in an experiment involving his brother and sister."], 1, "Get ready for a unique movie experience."];
  const before = [plot, ...commonBefore];
  const after = harder ? [
    ["obsession", "What is Victor obsessed with?", ["Making his brother immortal.", "Curing people.", "Conquering death."], 2, "What made him obsessed with this?"],
    ["harlander", "Why does Harlander decide to sponsor Victor's experiment?", ["William said Victor could cure his disease.", "Elizabeth asked him to do so.", "He saw Victor conducting an experiment to reanimate corpses."], 2, "What was his real intention?"],
    ["life", "How does the Creature come to life?", ["A lightning-powered machine reanimates one soldier's body.", "A gas-powered machine stitches together body parts.", "An electrical machine reanimates a body assembled from multiple corpses."], 2, "Is it a beautiful creature?"],
    ["explode", "Why does Victor decide to explode the laboratory and the Creature?", ["Elizabeth asks him to kill the Creature.", "The Creature killed Harlander.", "Victor considers it a failure because it cannot say more than 'Victor.'"], 2, "Was it fair? Did the Creature die?"],
    ["compassion", "What do Elizabeth and the blind old man have in common?", ["They both merely disagree with Victor.", "They torture the Creature.", "They are the only people who show it love and compassion."], 2, "Why did that happen? What happened to both of them?"],
    ["companion", "What does the Creature demand from Victor?", ["A master.", "Elizabeth's life.", "A companion."], 2, "Why? Is it fair?"],
    ["son", "What happens to Victor right before he dies?", ["He tells the captain to return home.", "He accepts the Creature as his master.", "He accepts the Creature as his son."], 2, "What happened to the Creature afterwards?"]
  ] : [
    ["obsession", "What is Victor's obsession?", ["Making his brother immortal.", "Helping people.", "Immortality."], 2, "What made him obsessed with this?"],
    ["harlander", "Why does Harlander pay for Victor's experiment?", ["William said Victor could cure him.", "Elizabeth asked him to meet Victor.", "He saw Victor conducting an experiment."], 2, "What was his real intention? Is he healthy?"],
    ["life", "How does the Creature come to life?", ["A solar-powered machine reanimates a body.", "A gas-powered machine uses soldiers' body parts.", "An electrical machine reanimates the body Victor collected."], 2, "How did Victor create its body?"],
    ["explode", "Why does Victor decide to explode the laboratory and the Creature?", ["Elizabeth asks him to.", "The Creature killed Harlander.", "Victor thinks the Creature and experiment are failures."], 2, "Was it fair? Did the Creature die?"],
    ["compassion", "What do Elizabeth and the blind old man have in common?", ["They disagree with Victor.", "They torture the Creature.", "They show love and compassion to the Creature."], 2, "Was Victor similar?"],
    ["companion", "What does the Creature want from Victor?", ["A brother.", "Elizabeth's life.", "A companion."], 2, "Why? Is it fair?"],
    ["son", "What happens to Victor right before he dies?", ["He tells the captain to return home.", "He accepts the Creature as his master.", "He accepts the Creature as his son."], 2, "What is his final advice?"]
  ];
  const interview = [["quick", "It was a quick process to transform the actor into the Creature.", ["True", "False"], 1, "It took hours."], ["realistic", "Mike wanted the Creature to look realistic.", ["False", "True"], 1, "He wanted viewers to see man's work."], ["eyes", "Del Toro says the eyes are not important.", ["True", "False"], 1, "He said the eyes are a key element."]];
  const during = harder ? ["Who is Victor, and how would you describe him?", "What is his ultimate goal?", "Does Victor achieve his goal?", "How is the movie divided?", "Who are Harlander, Elizabeth, and William?", "How are they important to the plot?", "Who is the monster in the story?"] : ["Who is Victor? Is he a good man?", "What is Victor's goal?", "Can you explain his experiment?", "How is the movie divided?", "Who are Harlander, Elizabeth, and William?", "How are they important to the plot?", "Who is the monster in the story?"];
  const facts = [["author", "A man wrote the book.", ["True", "False"], 1, "Mary Shelley wrote Frankenstein."], ["adaptations", "Frankenstein has only one movie adaptation.", ["True", "False"], 1, "The story has been adapted many times."], ["teenager", "A teenager wrote Frankenstein.", ["False", "True"], 1, "Mary Shelley began the story as a teenager."], ["name", "Frankenstein is the name of the Creature.", ["True", "False"], 1, "Frankenstein is the creator's family name."], ["1818", "The book was published in 1818.", ["False", "True"], 1, "Correct."]];
  const vocabPairs = [["Seek", "To try to find"], ["Devour", "To eat very quickly and hungrily"], ["Inevitable", "Something that cannot be avoided"], ["Humble", "Not proud or arrogant"], ["Merciless", "Harsh and cruel"], ["Charnel", "A place where dead bodies or bones are kept"], ["Indulge", "To enjoy something you like"], ["Conflagration", "A large and destructive fire"]];
  const defaults = { before:{}, after:{}, interview:{}, facts:{}, during:[], writing:"", name:"", teacher:"", orders:{}, wrong:{}, matches:[], selectedMatch:"", matchOrder:[] };
  let state; try { state = { ...defaults, ...JSON.parse(localStorage.getItem(key) || "{}") }; } catch { state = { ...defaults }; }
  state.orders ||= {}; state.wrong ||= {}; state.matches ||= []; state.matchOrder ||= [];
  const save = () => localStorage.setItem(key, JSON.stringify(state));
  const order = (group,id,options) => state.orders[`${group}-${id}`] ||= options.map((_,i)=>i).sort(()=>Math.random()-.5);
  function renderQuiz(selector, items, group) {
    const host=document.querySelector(selector); if(!host)return; const old=host.querySelector('.question-carousel')?.scrollLeft||0;
    host.innerHTML=`<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">&#8592;</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">&#8594;</button></div></div><div class="question-carousel">${items.map((q,i)=>{const answer=state[group][q[0]],correct=answer===q[3],wrong=state.wrong[`${group}-${q[0]}`]||[];return `<div class="question-slide"><p class="slide-number">Question ${i+1} of ${items.length}</p><article class="question-card ${correct?'is-correct':''}"><p class="question-text">${q[1]}</p><div class="answer-options">${order(group,q[0],q[2]).map((item,d)=>`<button class="answer-choice ${answer===item?'selected':''} ${wrong.includes(item)?'was-wrong':''}" data-group="${group}" data-id="${q[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65+d)}</span>${q[2][item]}</button>`).join('')}</div><p class="question-feedback">${answer===undefined?'':correct?`Correct. ${q[4]}`:'Not quite. Try another answer.'}</p></article></div>`}).join('')}</div></div>`; host.querySelector('.question-carousel').scrollLeft=old;
  }
  function renderMatching(){const host=document.querySelector('#extra-activity');if(!harder||!host)return;const all=vocabPairs.flatMap((pair,i)=>[[`w${i}`,pair[0],i],[`d${i}`,pair[1],i]]);if(!state.matchOrder.length)state.matchOrder=all.map(x=>x[0]).sort(()=>Math.random()-.5);const choices=state.matchOrder.map(id=>all.find(x=>x[0]===id));host.innerHTML=choices.map(([id,label,pair])=>`<button class="match-button ${state.matches.includes(pair)?'matched':''} ${state.selectedMatch===id?'selected':''}" data-match="${id}" data-pair="${pair}" data-match-color="${pair}" type="button">${label}</button>`).join('')+`<p class="completion-message">${state.matches.length===vocabPairs.length?'Excellent. Every word is matched.':`${state.matches.length} / ${vocabPairs.length} pairs matched`}</p>`}
  const total=before.length+after.length+during.length+(harder?interview.length+vocabPairs.length:facts.length)+1;
  function render(){renderQuiz('#before-questions',before,'before');renderQuiz('#after-questions',after,'after');harder?(renderQuiz('#interview-questions',interview,'interview'),renderMatching()):renderQuiz('#extra-activity',facts,'facts');document.querySelector('#during-checklist').innerHTML=during.map((q,i)=>`<button class="watch-item ${state.during.includes(i)?'done':''}" data-during="${i}" type="button"><span>${state.during.includes(i)?'✓':'○'}</span>${q}</button>`).join('');['student-writing','student-name','teacher-name'].forEach(id=>document.querySelector(`#${id}`).value=state[id==='student-writing'?'writing':id==='student-name'?'name':'teacher']);const writingDone=state.writing.trim().length>=50;document.querySelector('#writing-feedback').textContent=writingDone?'Response complete.':'Write at least 50 characters to complete this activity.';const groups=[['before',before],['after',after],['interview',harder?interview:[]],['facts',harder?[]:facts]];const quizCount=groups.reduce((n,[group,list])=>n+list.filter(q=>state[group]?.[q[0]]===q[3]).length,0);const done=quizCount+state.during.length+(harder?state.matches.length:0)+(writingDone?1:0);document.querySelector('#progress-label').textContent=`${done} / ${total} complete`;document.querySelector('#progress-bar').style.width=`${done/total*100}%`;save()}
  document.addEventListener('click',e=>{const c=e.target.closest('[data-group]');if(c){const group=c.dataset.group,id=c.dataset.id,answer=+c.dataset.answer,list=group==='before'?before:group==='after'?after:group==='interview'?interview:facts,q=list.find(x=>x[0]===id);state[group][id]=answer;if(answer!==q[3]){const k=`${group}-${id}`;state.wrong[k]=[...(state.wrong[k]||[]),answer]}render();return}const d=e.target.closest('[data-during]');if(d){const i=+d.dataset.during;state.during=state.during.includes(i)?state.during.filter(x=>x!==i):[...state.during,i];render();return}const m=e.target.closest('[data-match]');if(m&&!state.matches.includes(+m.dataset.pair)){if(!state.selectedMatch)state.selectedMatch=m.dataset.match;else{const first=document.querySelector(`[data-match="${state.selectedMatch}"]`);if(first&&first.dataset.pair===m.dataset.pair&&first.dataset.match!==m.dataset.match)state.matches.push(+m.dataset.pair);state.selectedMatch=''}render();return}const nav=e.target.closest('[data-nav]');if(nav){const car=nav.closest('.question-carousel-shell').querySelector('.question-carousel');car.scrollBy({left:car.clientWidth*(nav.dataset.nav==='next'?1:-1),behavior:'smooth'})}});
  ['student-writing','student-name','teacher-name'].forEach(id=>document.querySelector(`#${id}`).addEventListener('input',e=>{state[id==='student-writing'?'writing':id==='student-name'?'name':'teacher']=e.target.value;render()}));document.querySelector('#reset-lesson').addEventListener('click',()=>{if(confirm('Reset lesson progress?')){state={...defaults,before:{},after:{},interview:{},facts:{},during:[],orders:{},wrong:{},matches:[]};render()}});render();
})();
