(function () {
  if (window.__myeLessonExportsReady) return;
  window.__myeLessonExportsReady = true;
  const reportButton = document.querySelector("#save-report");
  const storyButton = document.querySelector("#share-story");
  if (!reportButton || !storyButton) return;

  const text = (selector, fallback = "") => document.querySelector(selector)?.textContent?.trim() || fallback;
  const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));
  const lessonTitle = document.body.dataset.reportTitle || text(".lesson-hero h1", "Movie lesson");
  const pathParts = location.pathname.split("/").filter(Boolean);
  const lastPathPart = pathParts.at(-1) || "movie-lesson";
  const lessonSlug = lastPathPart.endsWith(".html") ? (pathParts.at(-2) || "movie-lesson") : lastPathPart;
  const posterSource = document.querySelector(".hero-poster")?.getAttribute("src");

  function progressDetails() {
    const label = text("#progress-label", text(".progress-panel strong", "0 / 0 complete"));
    const match = label.match(/(\d+)\s*\/\s*(\d+)/);
    return { completed: Number(match?.[1] || 0), total: Number(match?.[2] || 0), label };
  }

  function openReport() {
    const popup = window.open("", "_blank");
    if (!popup) {
      document.querySelector("#story-status").textContent = "Please allow pop-ups to create your lesson report.";
      return;
    }
    const progress = progressDetails();
    const student = document.querySelector("#student-name")?.value?.trim() || "Not provided";
    const teacher = document.querySelector("#teacher-name")?.value?.trim() || "Not provided";
    const response = (document.querySelector("#student-writing") || document.querySelector(".writing-card textarea"))?.value?.trim() || "No written response submitted.";
    const logo = new URL("../assets/mye-logo.png", location.href).href;
    const poster = posterSource ? new URL(posterSource, location.href).href : "";
    popup.document.write(`<!doctype html><html><head><meta charset="UTF-8"><title>${escapeHtml(lessonTitle)} lesson report</title><style>@page{size:auto;margin:14mm}*{box-sizing:border-box}body{max-width:780px;margin:0 auto;color:#102121;font-family:Arial,sans-serif}.head{display:flex;align-items:center;gap:16px;padding-bottom:18px;border-bottom:1px solid #b9d8d6}.head img{width:62px;height:62px;border-radius:50%}.eyebrow{margin:0 0 5px;color:#087f7b;font-size:10px;font-weight:bold;letter-spacing:1.4px;text-transform:uppercase}h1{margin:0;font-size:30px}.student{margin:7px 0 0;color:#58706f}.summary{display:flex;justify-content:space-between;align-items:center;margin:24px 0;padding:21px 23px;border-radius:20px;background:linear-gradient(120deg,#cafff7,#d9ff00)}.summary p{margin:0 0 5px;font-size:12px;font-weight:bold}.summary strong{font-size:27px}.summary img{width:76px;height:108px;border-radius:8px;object-fit:cover}.bar{height:12px;overflow:hidden;border-radius:999px;background:#e3eeed}.bar span{display:block;height:100%;border-radius:inherit;background:#16b9b4}.writing{margin-top:29px;padding:23px;border:1px solid #cde6e4;border-radius:19px;background:#f1fffd}.writing h2{margin:0 0 8px}.writing blockquote{min-height:72px;margin:14px 0 0;padding:12px 15px;border-radius:12px;background:#fff;box-shadow:inset 0 0 0 1px #d9e8e7;white-space:pre-wrap}.foot{margin-top:28px;padding-top:16px;border-top:1px solid #d4e2e1;color:#607674;font-size:11px}@media print{.summary,.bar span{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><header class="head"><img src="${logo}" alt="Movie Your English logo"><div><p class="eyebrow">Movie Your English lesson report</p><h1>${escapeHtml(lessonTitle)}</h1><p class="student">Student: ${escapeHtml(student)} &middot; Teacher: ${escapeHtml(teacher)}</p></div></header><section class="summary"><div><p>LESSON PROGRESS</p><strong>${progress.completed} / ${progress.total} complete</strong></div>${poster ? `<img src="${poster}" alt="">` : ""}</section><div class="bar"><span style="width:${progress.total ? progress.completed / progress.total * 100 : 0}%"></span></div><section class="writing"><p class="eyebrow">Writing response</p><h2>${escapeHtml(text(".writing-card h2", "Your response"))}</h2><blockquote>${escapeHtml(response)}</blockquote></section><footer class="foot">Generated by Movie Your English. Save this report as a PDF and share it with your teacher.</footer></body></html>`);
    popup.document.close();
    window.setTimeout(() => popup.print(), 450);
  }

  const loadImage = (source) => new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = reject;
    image.src = new URL(source, location.href).href;
  });
  function drawCover(context, image, x, y, width, height) {
    const scale = Math.max(width / image.width, height / image.height);
    const sourceWidth = width / scale, sourceHeight = height / scale;
    context.drawImage(image, (image.width - sourceWidth) / 2, (image.height - sourceHeight) / 2, sourceWidth, sourceHeight, x, y, width, height);
  }
  async function createStory() {
    const status = document.querySelector("#story-status");
    storyButton.disabled = true;
    status.textContent = "Creating your Story image…";
    try {
      if (!posterSource) throw new Error("Poster unavailable");
      const [template, poster] = await Promise.all([loadImage("../assets/mye-instagram-story-template.png"), loadImage(posterSource)]);
      const canvas = document.createElement("canvas"), context = canvas.getContext("2d"), progress = progressDetails();
      canvas.width = 1080; canvas.height = 1920;
      context.drawImage(template, 0, 0, 1080, 1920);
      context.fillStyle = "#fff"; context.fillRect(325, 555, 430, 670);
      drawCover(context, poster, 345, 575, 390, 630);
      context.fillStyle = "#fff"; context.textAlign = "center";
      context.font = "700 42px Arial"; context.fillText("I've just practiced English with", 540, 485);
      context.font = "800 46px Arial"; context.fillText(lessonTitle, 540, 1285);
      context.font = "700 31px Arial"; context.fillText(`I completed ${progress.completed} of ${progress.total} activities!`, 540, 1345);
      const blob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
      if (!blob) throw new Error("Image unavailable");
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob); link.download = `${lessonSlug}-instagram-story.png`; link.click();
      window.setTimeout(() => URL.revokeObjectURL(link.href), 1000);
      status.textContent = "Story image downloaded. Add it to your Instagram Story!";
    } catch {
      status.textContent = "We couldn't create the Story image. Please try again.";
    } finally {
      storyButton.disabled = false;
    }
  }

  reportButton.addEventListener("click", (event) => { event.stopImmediatePropagation(); openReport(); }, true);
  storyButton.addEventListener("click", (event) => { event.stopImmediatePropagation(); createStory(); }, true);
})();
