const key = "mye-the-wrong-paris-v1", totalActivities = 31;
const defaults = { before: {}, sorted: {}, selected: "", during: [], after: {}, writing: "", name: "", teacher: "", orders: {}, sortOrder: [] };
let saved = {}; try { saved = JSON.parse(localStorage.getItem(key) || "{}"); } catch { localStorage.removeItem(key); } let state = { ...defaults, ...saved, sorted: { ...(saved.sorted || {}) }, orders: { ...(saved.orders || {}) } };
const before = [
  ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["A woman accidentally joins a survival show in Paris, Texas, and must escape to find love.", "A woman expects a dating show in Paris, Texas, but arrives in Paris, France.", "A woman expects a dating show in Paris, France, but lands in Paris, Texas, where a cowboy may help her."], 2, "Get ready for a fun experience in Paris!"],
  ["paris", "She dreams of studying French art in ________ one day.", ["Rome", "Texas", "Paris", "Vienna"], 2, "Would you like to visit Paris?"],
  ["honey", "The beekeeper fills the pot with _______ every day.", ["tea", "chocolate", "honey", "coffee"], 2, "Do you like honey?"],
  ["tuition", "________ is the money you pay to attend a school, college, or university.", ["Prize", "Salary", "Tuition", "Fortune"], 2, "Are tuition fees expensive in your city?"],
  ["ranch", "The _______ spent his days working on the _______ surrounded by _______.", ["cowboy – street – airplanes", "cowgirl – computers – elephants", "cowboy – ranch – horses", "cowgirl – farm – paintings"], 2, "Is it nice to live on a ranch?"],
  ["barn", "A(n) _______ is a large building on a farm used to shelter animals.", ["acre", "bar", "barn", "house"], 2, "What else can you keep in a barn?"],
  ["hay", "Horses eat fresh _______.", ["hey", "say", "hay", "may"], 2, "Do you like horses?"]
];
const after = [
  ["dawn", "Who is Dawn?", ["A TV producer.", "A French student.", "An artist."], 2, "Does she have a good family?"],
  ["dream", "What is Dawn's dream?", ["Become a cowgirl.", "Participate in a reality show.", "Study art in Paris."], 2, "Why does she not go to Paris?"],
  ["honeypot", "What is The Honeypot?", ["A show that finds boyfriends for every participant.", "A show with a five-million-dollar prize.", "A show where women compete for one man's love."], 2, "Is it a good reality show?"],
  ["trick", "What is the main trick of the show?", ["The contestants expect Paris, Texas, but go to France.", "They expect a cowboy but meet a French artist.", "They expect Paris, France, but the show is in Paris, Texas."], 2, "Would you participate?"],
  ["meet", "Where does Dawn meet Trey?", ["On a farm.", "In a barn.", "At a bar."], 2, "Do they like each other?"],
  ["plan", "What is Dawn's plan on the show?", ["Seduce Trey and remain in Texas.", "Eliminate Lexie.", "Be eliminated quickly."], 2, "Why does she want that?"],
  ["finale", "What happens in the finale?", ["Trey chooses Lexie.", "Dawn studies art in Paris alone.", "Trey and Dawn finish the show happy and together."], 2, "Where are they at the end?"]
];
const during = ["Who is Dawn, and what is her dream?", "Who is Trey, and where is he from?", "What is The Honeypot?", "Is joining The Honeypot a good idea?", "Who are Rachel, Lexie, and Nicole?", "Does the movie have a happy ending?"];
const sortItems = [
  ["museums", "Art Museums", "france"], ["croissant", "Croissant", "france"], ["eiffel", "Eiffel Tower", "france"], ["heels", "High Heels", "france"], ["cafe", "Café", "france"],
  ["cows", "Cows", "texas"], ["hay", "Hay", "texas"], ["ranch", "Ranch", "texas"], ["spurs", "Spurs", "texas"], ["barn", "Barn", "texas"]
];
const save = () => localStorage.setItem(key, JSON.stringify(state)), count = (object) => Object.keys(object).length, writingComplete = () => state.writing.trim().length >= 50;
if (!state.sortOrder.length) { state.sortOrder = sortItems.map(([id]) => id).sort(() => Math.random() - .5); save(); }
const progress = () => count(state.before) + count(state.sorted) + state.during.length + count(state.after) + (writingComplete() ? 1 : 0);
function order(group, id, options) { const k = `${group}-${id}`; if (!state.orders[k]) { state.orders[k] = options.map((_, i) => i).sort(() => Math.random() - .5); save(); } return state.orders[k]; }
function renderQuiz(target, items, group) { const host = document.querySelector(target), position = host.querySelector(".question-carousel")?.scrollLeft || 0; host.innerHTML = `<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">&#8592;</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">&#8594;</button></div></div><div class="question-carousel">${items.map((q, i) => { const answer = state[group][q[0]], correct = answer === q[3]; return `<div class="question-slide"><p class="slide-number">Question ${i + 1} of ${items.length}</p><article class="question-card ${correct ? "is-correct" : ""}"><p class="question-text">${q[1]}</p><div class="answer-options">${order(group, q[0], q[2]).map((item, display) => `<button class="answer-choice ${answer === item ? "selected" : ""}" data-group="${group}" data-id="${q[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65 + display)}</span>${q[2][item]}</button>`).join("")}</div><p class="question-feedback">${answer === undefined ? "" : correct ? `Correct. ${q[4]}` : "Not quite. Try another answer."}</p></article></div>`; }).join("")}</div></div>`; host.querySelector(".question-carousel").scrollLeft = position; }
function renderSort() { const item = (id) => sortItems.find(([value]) => value === id); document.querySelector("#paris-sort-bank").innerHTML = state.sortOrder.filter((id) => !state.sorted[id]).map((id) => { const [, label] = item(id); return `<button class="paris-sort-chip ${state.selected === id ? "is-selected" : ""}" draggable="true" type="button" data-sort-item="${id}">${label}</button>`; }).join("") || "<p>Every item has been placed.</p>"; ["france", "texas"].forEach((zone) => { document.querySelector(`#${zone}-items`).innerHTML = state.sortOrder.filter((id) => state.sorted[id] === zone).map((id) => `<button type="button" data-return-item="${id}">${item(id)[1]}</button>`).join(""); }); document.querySelector("#paris-sort-feedback").textContent = count(state.sorted) === sortItems.length ? "Excellent. You found the right Paris for every item." : `${count(state.sorted)} / ${sortItems.length} items sorted`; }
function place(id, zone) { const correct = sortItems.find(([value]) => value === id)?.[2]; if (correct === zone) state.sorted[id] = zone; state.selected = ""; save(); render(); }
function render() { renderQuiz("#before-questions", before, "before"); renderQuiz("#after-questions", after, "after"); renderSort(); document.querySelector("#during-checklist").innerHTML = during.map((item, i) => `<button class="watch-item ${state.during.includes(i) ? "done" : ""}" data-during="${i}" type="button"><span>${state.during.includes(i) ? "✓" : "○"}</span>${item}</button>`).join(""); document.querySelector("#student-writing").value = state.writing; document.querySelector("#student-name").value = state.name; document.querySelector("#teacher-name").value = state.teacher; document.querySelector("#writing-feedback").textContent = writingComplete() ? "Writing task complete." : "Write at least 50 characters to complete this activity."; const completed = progress(); document.querySelector("#progress-label").textContent = `${completed} / ${totalActivities} complete`; document.querySelector("#progress-bar").style.width = `${completed / totalActivities * 100}%`; }
document.addEventListener("click", (event) => { const choice = event.target.closest("[data-group]"); if (choice) { state[choice.dataset.group][choice.dataset.id] = +choice.dataset.answer; save(); render(); return; } const chip = event.target.closest("[data-sort-item]"); if (chip) { state.selected = state.selected === chip.dataset.sortItem ? "" : chip.dataset.sortItem; save(); render(); return; } const zone = event.target.closest("[data-paris-zone]"); if (zone && state.selected) { place(state.selected, zone.dataset.parisZone); return; } const returned = event.target.closest("[data-return-item]"); if (returned) { delete state.sorted[returned.dataset.returnItem]; save(); render(); return; } const watch = event.target.closest("[data-during]"); if (watch) { const i = +watch.dataset.during; state.during = state.during.includes(i) ? state.during.filter((value) => value !== i) : [...state.during, i]; save(); render(); return; } const nav = event.target.closest("[data-nav]"); if (nav) { const carousel = nav.closest(".question-carousel-shell").querySelector(".question-carousel"); carousel.scrollBy({ left: carousel.clientWidth * (nav.dataset.nav === "next" ? 1 : -1), behavior: "smooth" }); } });
document.addEventListener("dragstart", (event) => { const chip = event.target.closest("[data-sort-item]"); if (chip) event.dataTransfer.setData("text/plain", chip.dataset.sortItem); }); document.querySelectorAll("[data-paris-zone]").forEach((zone) => { zone.addEventListener("dragover", (event) => event.preventDefault()); zone.addEventListener("drop", (event) => { event.preventDefault(); place(event.dataTransfer.getData("text/plain"), zone.dataset.parisZone); }); });
document.querySelectorAll("[data-paris-zone]").forEach((zone) => zone.addEventListener("keydown", (event) => { if ((event.key === "Enter" || event.key === " ") && state.selected) { event.preventDefault(); place(state.selected, zone.dataset.parisZone); } }));
["student-writing", "student-name", "teacher-name"].forEach((id) => document.querySelector(`#${id}`).addEventListener("input", (event) => { state[id === "student-writing" ? "writing" : id === "student-name" ? "name" : "teacher"] = event.target.value; save(); render(); })); document.querySelector("#reset-lesson").addEventListener("click", () => { if (confirm("Reset lesson progress?")) { state = { ...defaults, before: {}, sorted: {}, selected: "", during: [], after: {}, orders: {}, sortOrder: sortItems.map(([id]) => id).sort(() => Math.random() - .5) }; save(); render(); } }); render();
