const key = "mye-harry-potter-philosophers-stone-v1", totalActivities = 32;
const verbs = ["tell", "studies", "learn", "face", "discover", "are", "is"];
const defaults = { before: {}, verbs: Array(verbs.length).fill(null), verbOrder: [], during: [], after: {}, scene: {}, writing: "", name: "", teacher: "", orders: {} };
let saved = {}; try { saved = JSON.parse(localStorage.getItem(key) || "{}"); } catch { localStorage.removeItem(key); } let state = { ...defaults, ...saved, verbs: Array.isArray(saved.verbs) ? saved.verbs : [...defaults.verbs], orders: { ...(saved.orders || {}) } };
const before = [
  ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["Harry joins a wizarding school with his parents to become a teacher.", "On his 23rd birthday, Harry moves to a school to help his mother fight an evil wizard.", "Harry learns he is a wizard, studies at Hogwarts, and faces new adventures with his friends."], 2, "Get ready for the amazing first Harry Potter movie!"],
  ["wizard", "A __________ is a person who possesses magical powers and uses them to perform spells.", ["lizard", "wizardry", "wizard", "magic"], 2, "Would you like to be a wizard?"],
  ["wand", "A ___________ is a piece of wood used as a tool in spells.", ["cloak", "magician", "wand", "hat"], 2, "What other objects can represent magic?"],
  ["chess", "She taught her younger brother how to play __________, explaining each piece’s unique moves.", ["soccer", "cheese", "chess", "polo"], 2, "Do you play chess?"],
  ["broom", "A __________ is the object that witches use to fly through the air.", ["boom", "groom", "broom", "bloom"], 2, "Would you have the courage to fly on one?"],
  ["scar", "Harry has a _________ in the shape of a lightning bolt on his forehead.", ["lightning", "knife", "scar", "enemy"], 2, "Do you have any scars?"],
  ["blackmagic", "Black magic refers to...", ["a celebration of magical power.", "using powers for the good of a city.", "using supernatural powers or magic for evil and selfish purposes.", "the good intentions in a wizard’s heart."], 2, "Is black magic real, in your opinion?"]
];
const after = [
  ["home", "How is Harry’s life at his aunt’s house?", ["Terrific, with parties, zoo trips, and presents.", "Okay; he lives in a decent room.", "Terrible; he lives in a cupboard and cannot do anything fun."], 2, "Is his life good?"],
  ["hagrid", "Who is Hagrid?", ["An unpleasant Slytherin student and Harry’s rival.", "The Hogwarts headmaster who takes Harry there.", "The keeper of the keys who rescues Harry from the Dursleys."], 2, "Is Hagrid a good person?"],
  ["friends", "Who are Hermione and Ronnie?", ["Experienced students who welcome Harry.", "Two arrogant Slytherin students.", "Two insecure first-year students who become Harry’s friends."], 2, "Do you like them?"],
  ["fluffy", "What is Fluffy guarding, and how can they get past him?", ["Dumbledore’s stone; they need a magical harp.", "Many secrets; only Hagrid knows the way.", "The Philosopher’s Stone; relaxing music is his weakness."], 2, "How do they get past Fluffy?"],
  ["chess", "How does Ronnie win the wizard chess match?", ["By transforming Harry into a king.", "By sacrificing Hermione’s rook.", "By sacrificing himself and his knight."], 2, "His move creates an opening for Harry’s checkmate."],
  ["voldemort", "Who is Voldemort?", ["Hagrid’s three-headed dog.", "The Hogwarts headmaster.", "A dark wizard who murdered Harry’s parents."], 2, "Do people mention his name?"],
  ["quirrell", "How does Professor Quirrell die?", ["Voldemort leaves him without enough strength.", "His skin freezes when he touches Harry.", "His skin becomes rock-like when Harry touches him."], 2, "Harry notices this and touches him on purpose."]
];
const scene = [["blind", "Hermione implies Ronnie can blind someone.", ["False", "True"], 1, "How do you know?"], ["grammar", "Hermione corrects Ronnie’s grammar mistake.", ["True", "False"], 1, "Does she correct grammar or pronunciation?"], ["nailed", "Hermione nailed the task.", ["False", "True"], 1, "Is she a good student?"], ["letter", "Harry says they will need another letter.", ["True", "False"], 1, "They need another feather, not a letter."]];
const during = ["What is Harry’s family like?", "Who are Ronnie, Hermione, and Draco?", "How does Harry adapt to Hogwarts? Are all the teachers good?", "What is Quidditch?", "Who are Hagrid and Fluffy?", "Which magical objects do they have at Hogwarts?"];
const save = () => localStorage.setItem(key, JSON.stringify(state)), count = (object) => Object.keys(object).length, writingComplete = () => state.writing.trim().length >= 50;
if (!state.verbOrder.length) { state.verbOrder = [...verbs].sort(() => Math.random() - .5); save(); }
const progress = () => count(state.before) + state.verbs.filter(Boolean).length + state.during.length + count(state.after) + count(state.scene) + (writingComplete() ? 1 : 0);
function order(group, id, options) { const k = `${group}-${id}`; if (!state.orders[k]) { state.orders[k] = options.map((_, i) => i).sort(() => Math.random() - .5); save(); } return state.orders[k]; }
function renderQuiz(target, items, group) { const host = document.querySelector(target), position = host.querySelector(".question-carousel")?.scrollLeft || 0; host.innerHTML = `<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">&#8592;</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">&#8594;</button></div></div><div class="question-carousel">${items.map((q, i) => { const answer = state[group][q[0]], correct = answer === q[3]; return `<div class="question-slide"><p class="slide-number">Question ${i + 1} of ${items.length}</p><article class="question-card ${correct ? "is-correct" : ""}"><p class="question-text">${q[1]}</p><div class="answer-options">${order(group, q[0], q[2]).map((item, display) => `<button class="answer-choice ${answer === item ? "selected" : ""}" data-group="${group}" data-id="${q[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65 + display)}</span>${q[2][item]}</button>`).join("")}</div><p class="question-feedback">${answer === undefined ? "" : correct ? `Correct. ${q[4]}` : "Not quite. Try another answer."}</p></article></div>`; }).join("")}</div></div>`; host.querySelector(".question-carousel").scrollLeft = position; }
function render() { renderQuiz("#before-questions", before, "before"); renderQuiz("#after-questions", after, "after"); renderQuiz("#scene-questions", scene, "scene"); document.querySelectorAll("[data-slot]").forEach((slot) => { const value = state.verbs[+slot.dataset.slot]; slot.textContent = value || "_____"; slot.classList.toggle("is-filled", Boolean(value)); }); const used = new Set(state.verbs.filter(Boolean)); document.querySelector("#verb-bank").innerHTML = state.verbOrder.filter((verb) => !used.has(verb)).map((verb) => `<button type="button" data-verb="${verb}">${verb}</button>`).join(""); const correct = state.verbs.filter((verb, i) => verb === verbs[i]).length; document.querySelector("#verb-feedback").textContent = correct === verbs.length ? "Excellent. Every present-tense verb is correct." : `${correct} / ${verbs.length} verbs in the correct gap`; document.querySelector("#during-checklist").innerHTML = during.map((item, i) => `<button class="watch-item ${state.during.includes(i) ? "done" : ""}" data-during="${i}" type="button"><span>${state.during.includes(i) ? "✓" : "○"}</span>${item}</button>`).join(""); document.querySelector("#student-writing").value = state.writing; document.querySelector("#student-name").value = state.name; document.querySelector("#teacher-name").value = state.teacher; document.querySelector("#writing-feedback").textContent = writingComplete() ? "Writing task complete." : "Write at least 50 characters to complete this activity."; const completed = progress(); document.querySelector("#progress-label").textContent = `${completed} / ${totalActivities} complete`; document.querySelector("#progress-bar").style.width = `${completed / totalActivities * 100}%`; }
document.addEventListener("click", (event) => { const choice = event.target.closest("[data-group]"); if (choice) { state[choice.dataset.group][choice.dataset.id] = +choice.dataset.answer; save(); render(); return; } const verb = event.target.closest("[data-verb]"); if (verb) { const empty = state.verbs.findIndex((item) => !item); if (empty >= 0) state.verbs[empty] = verb.dataset.verb; save(); render(); return; } const slot = event.target.closest("[data-slot]"); if (slot && state.verbs[+slot.dataset.slot]) { state.verbs[+slot.dataset.slot] = null; save(); render(); return; } const watch = event.target.closest("[data-during]"); if (watch) { const i = +watch.dataset.during; state.during = state.during.includes(i) ? state.during.filter((value) => value !== i) : [...state.during, i]; save(); render(); return; } const nav = event.target.closest("[data-nav]"); if (nav) { const carousel = nav.closest(".question-carousel-shell").querySelector(".question-carousel"); carousel.scrollBy({ left: carousel.clientWidth * (nav.dataset.nav === "next" ? 1 : -1), behavior: "smooth" }); } });
["student-writing", "student-name", "teacher-name"].forEach((id) => document.querySelector(`#${id}`).addEventListener("input", (event) => { state[id === "student-writing" ? "writing" : id === "student-name" ? "name" : "teacher"] = event.target.value; save(); render(); })); document.querySelector("#reset-lesson").addEventListener("click", () => { if (confirm("Reset lesson progress?")) { state = { ...defaults, before: {}, verbs: Array(verbs.length).fill(null), verbOrder: [...verbs].sort(() => Math.random() - .5), during: [], after: {}, scene: {}, orders: {} }; save(); render(); } }); render();
