const key = "mye-odyssey-v1";
let state = { before:{}, verbs:[null,null,null,null,null], during:[], characters:[], after:{}, bts:{}, writing:"", name:"", teacher:"", orders:{} };
Object.assign(state, JSON.parse(localStorage.getItem(key)||"{}"));
const before=[
 ["plot","Based on the trailer, which plot is correct?",["After a war, a man faces a dangerous voyage back home, meeting mythical creatures along the way.","After a war, a family faces mythical creatures on their way home.","After a violent war, a group of men return home to save their island from an invasion of mythical creatures."],0,"Get ready for an epic adventure!"],
 ["island","A(n) ________ is a piece of land completely surrounded by the sea.",["island","land","home","city"],0,"Have you ever visited any islands?"],
 ["horse","She learned how to ride a _______ when she was ten.",["horse","boat","throne","bow"],0,"Do you like horses?"],
 ["gods","In Greek mythology, __________ is the god of the sea and __________ is the god of the sky.",["Poseidon - Zeus","Zeus - Athena","Athena - Calypso","Poseidon - Hades"],0,"Do you know anything else about Greek gods?"],
 ["myth","Which option is not a creature from Greek mythology?",["Thunderbird","Centaurs","Sirens","Cyclops"],0,"This one is related to Native American mythology."],
 ["suitors","The princess had many ________ from different kingdoms interested in marrying her.",["suitors","masters","soldiers","swineherds"],0,"Was it easy for a woman to get married in the past?"],
 ["trick","The verbs deceive, trick, and fool all mean...",["to make someone believe something that is not true.","to force someone to believe something false.","to make someone buy something unsuitable for their job.","to make someone believe you because you are a good leader."],0,"Have you ever tricked anyone?"]];
const after=[["goal","What is Odysseus's goal?",["He wants to get home.","He plans to destroy Ithaca.","His goal is to kill Agamemnon."],0,"And where is his home?"],["ithaca","How is Ithaca while Odysseus is away?",["It's chaotic and full of suitors.","It's very stable and safe for his family.","It's protected by Eumaeus and Argos."],0,"What do the suitors want?"],["war","Why did Odysseus depart from Ithaca?",["He followed Agamemnon into war.","He wanted revenge against Poseidon.","He was searching for a horse statue."],0,"Was he important in the Trojan War?"],["voyage","What happens after the war in Troy?",["He travels around many islands trying to get home.","He returns home safe and sound.","He loses all his men after invading Calypso's home."],0,"Which adventures were the longest, hardest, and scariest?"],["poseidon","Why was Odysseus allegedly so unlucky on his journey home?",["He provoked Poseidon by blinding his son.","He tried to marry Athena.","He was not loyal to his men."],0,"Was it necessary to do that?"],["penelope","How does Penelope find out Odysseus is back?",["She asks challengers to string a bow and fire an arrow.","She asks Odysseus about Telemachus.","She talks to Calypso."],0,"What happens after this challenge?"]];
const bts=[["damon","Matt Damon says it is the biggest movie of his career.",["True","False"],0,"Do you know other movies he has made?"],["zendaya","Zendaya says the director can mix different genres in one movie.",["True","False"],0,"Did you feel that during the movie?"],["holland","According to Tom Holland, Christopher Nolan still has a lot to learn.",["True","False"],1,"Is he an experienced director? Do you like his movies?"],["pattinson","Robert mentioned he was not looking forward to watching the movie.",["True","False"],1,"He said the opposite."]];
const chars=[["Odysseus","A legendary warrior"],["Penelope","Odysseus's wife"],["Telemachus","Odysseus's son"],["Antinous","One of Penelope's suitors"],["Argos","Odysseus's dog"],["Eumaeus","Odysseus's loyal friend"],["Agamemnon","The commander of Odysseus"],["Menelaus","Agamemnon's brother"],["Eurylochus","One of Odysseus's men"]]; const verbs=["tried","faced","visited","met","became"]; const during=["Who is Odysseus? What is his goal?","Does he have a family?","What is Ithaca?","What happens in Troy?","What places do they visit? Do they have good experiences?","What is Zeus's law?","Who are Calypso and Agamemnon?"];
let selectedChar=null, selectedVerb=null;
const save=()=>{localStorage.setItem(key,JSON.stringify(state));renderProgress();}; const count=(o)=>Object.keys(o).length; const progress=()=>count(state.before)+state.verbs.filter(Boolean).length+state.during.length+state.characters.length+count(state.after)+count(state.bts)+(state.writing.trim().length>=50?1:0);
function optionOrder(group, id, options) { const orderKey = `${group}-${id}`; if (!state.orders[orderKey]) state.orders[orderKey] = options.map((_, index) => index).sort(() => Math.random() - 0.5); return state.orders[orderKey]; }
function quiz(id,items,group){document.querySelector(id).innerHTML=`<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-qnav="previous">←</button><button class="question-carousel-button" data-qnav="next">→</button></div></div><div class="question-carousel">${items.map((q,i)=>{let a=state[group][q[0]],ok=a===q[3],fb=a===undefined?"":ok?`Correct. ${q[4]}`:"Not quite. Try another answer.",order=optionOrder(group,q[0],q[2]);return `<div class="question-slide"><p class="slide-number">Question ${i+1} of ${items.length}</p><article class="question-card ${ok?"is-correct":""}"><p class="question-text">${q[1]}</p><div class="answer-options">${order.map((n,display)=>`<button class="answer-choice ${a===n?"selected":""}" data-g="${group}" data-id="${q[0]}" data-n="${n}"><span>${String.fromCharCode(65+display)}</span>${q[2][n]}</button>`).join("")}</div><p class="question-feedback">${fb}</p></article></div>`}).join("")}</div></div>`;}
function render(){quiz("#before-questions",before,"before");quiz("#after-questions",after,"after");quiz("#bts-questions",bts,"bts");document.querySelector("#during-checklist").innerHTML=during.map((x,i)=>`<button class="watch-item ${state.during.includes(i)?"done":""}" data-d="${i}"><span>${state.during.includes(i)?"✓":"○"}</span>${x}</button>`).join("");const matched=new Set(state.characters),nameOrder=optionOrder("characters","names",chars),definitionOrder=optionOrder("characters","definitions",chars);document.querySelector("#characters").innerHTML=nameOrder.map(i=>{const x=chars[i];return `<button class="match-button term-button ${selectedChar===x[0]?"selected":""} ${matched.has(x[0])?"matched":""}" data-c="${x[0]}">${x[0]}</button>`;}).join("");document.querySelector("#character-definitions").innerHTML=definitionOrder.map(i=>{const x=chars[i];return `<button class="match-button ${matched.has(x[0])?"matched":""}" data-cd="${x[0]}">${x[1]}</button>`;}).join("");document.querySelector("#character-count").textContent=matched.size;document.querySelectorAll(".verb-slot").forEach((e,i)=>e.textContent=state.verbs[i]||"_____");document.querySelector("#verb-bank").innerHTML=verbs.filter(v=>!state.verbs.includes(v)).map(v=>`<button class="match-button" data-v="${v}">${v}</button>`).join("");document.querySelector("#student-writing").value=state.writing;document.querySelector("#writing-feedback").textContent=state.writing.trim().length>=50?"Writing task complete.":"Write at least 50 characters to complete this activity.";renderProgress();}
function renderProgress(){let p=progress();document.querySelector("#progress-label").textContent=`${p} / 39 complete`;document.querySelector("#progress-bar").style.width=`${p/39*100}%`;}
document.addEventListener("click",e=>{let q=e.target.closest("[data-g]");if(q){let car=q.closest(".question-carousel"),pos=Math.round(car.scrollLeft/car.clientWidth),group=q.dataset.g;state[group][q.dataset.id]=+q.dataset.n;save();render();let refreshed=document.querySelector(group==="before"?"#before-questions .question-carousel":group==="after"?"#after-questions .question-carousel":"#bts-questions .question-carousel");if(refreshed)refreshed.scrollLeft=pos*refreshed.clientWidth;return;}let d=e.target.closest("[data-d]");if(d){let n=+d.dataset.d;state.during=state.during.includes(n)?state.during.filter(x=>x!==n):[...state.during,n];save();render();return;}let c=e.target.closest("[data-c]");if(c){selectedChar=c.dataset.c;render();return;}let cd=e.target.closest("[data-cd]");if(cd&&selectedChar){if(cd.dataset.cd===selectedChar)state.characters=[...new Set([...state.characters,selectedChar])];selectedChar=null;save();render();return;}let v=e.target.closest("[data-v]");if(v){let slot=state.verbs.findIndex(x=>!x);if(slot>=0)state.verbs[slot]=v.dataset.v;save();render();return;}let slot=e.target.closest("[data-slot]");if(slot&&state.verbs[+slot.dataset.slot]){state.verbs[+slot.dataset.slot]=null;save();render();}let nav=e.target.closest("[data-qnav]");if(nav){let car=nav.closest(".question-carousel-shell").querySelector(".question-carousel");car.scrollBy({left:car.clientWidth*(nav.dataset.qnav==="next"?1:-1),behavior:"smooth"});}});
["student-writing","student-name","teacher-name"].forEach(id=>document.querySelector(`#${id}`).addEventListener("input",e=>{state[id==="student-writing"?"writing":id==="student-name"?"name":"teacher"]=e.target.value;save();render();}));document.querySelector("#reset-lesson").addEventListener("click",()=>{if(confirm("Reset lesson progress?")){state={before:{},verbs:[null,null,null,null,null],during:[],characters:[],after:{},bts:{},writing:"",name:"",teacher:"",orders:{}};save();render();}});document.querySelector("#save-report").addEventListener("click",()=>window.print());render();
document.querySelector("#share-story")?.addEventListener("click",async()=>{const s=document.querySelector("#story-status");s.textContent="Creating your Story image…";try{const load=(src)=>new Promise((ok,bad)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=bad;i.src=new URL(src,location.href)}),[t,p]=await Promise.all([load("../assets/mye-instagram-story-template.png"),load("../assets/the-odyssey-poster.webp")]),c=document.createElement("canvas"),x=c.getContext("2d");c.width=1080;c.height=1920;x.drawImage(t,0,0,1080,1920);x.fillStyle="#fff";x.fillRect(345,605,390,585);x.drawImage(p,360,620,360,540);x.fillStyle="#fff";x.font="800 33px Arial";x.textAlign="center";x.fillText(`I completed ${progress()} of 39 activities!`,540,1320);const b=await new Promise(ok=>c.toBlob(ok,"image/png")),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="the-odyssey-story.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);s.textContent="Story image downloaded."}catch{s.textContent="We couldn't create the Story image. Please try again."}});render();
