(function () {
  const key = "mye-gladiator-2-v1", totalActivities = 27;
  const before = [
    ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["After slaves capture him, a man becomes a gladiator to save his wife and Milan.", "After they are captured, a couple enters the Colosseum to save their children from the emperor.", "After he is captured, a man is forced to enter the Colosseum and must save himself and Rome."], 2, "Get ready for a fantastic historical experience!", ["The story is set in Rome, and he is not fighting to save his wife.", "There is one central gladiator rather than a couple, and no children are part of this plot."]],
    ["rome", "________ is the capital city of Italy.", ["Venice", "Milan", "Rome", "Vienna"], 2, "Would you like to visit Rome?"],
    ["empire", "The Roman ________ was a powerful civilization that ruled large parts of Europe, North Africa, and the Middle East.", ["Attire", "Entire", "Empire", "Spire"], 2, "Was it a big empire?"],
    ["sword", "The gladiator drew his ________ and prepared for battle.", ["pistol", "sandals", "sword", "honor"], 2, "Is it easy to handle a sword?"],
    ["general", "A Roman ________ was a high-ranking military leader.", ["Generally", "Generator", "General", "Degenerate"], 2, "Would you like to command soldiers?"],
    ["overthrow", "The rebels planned to ________ the corrupt dictator.", ["throw away", "throw over", "overthrow", "underthrow"], 2, "To overthrow means to remove a leader or government from power."],
    ["riot", "A riot is...", ["an alternative protest against good companies.", "a peaceful protest by a large group.", "a violent and chaotic protest by a large group.", "a group of offensive words chanted in public."], 2, "Have you seen any riots recently?"]
  ];
  const after = [
    ["hanno", "Who is Hanno?", ["Arishat's son.", "Lucius's twin brother.", "The son of Maximus and Lucilla."], 2, "Hanno's birth name is Lucius."],
    ["revenge", "Why does Lucius want revenge against General Acacius?", ["Because Macrinus promised revenge to Lucius.", "Because Acacius killed Lucius's mother.", "Because Arishat was killed under Acacius's command."], 2, "Is his desire for revenge justifiable?"],
    ["plan", "What is Acacius and Lucilla's plan?", ["They plan to kill the emperors and end the Roman Empire.", "They plan to get rid of Macrinus.", "They plot to overthrow the emperors."], 2, "What goes wrong with their plan?"],
    ["ambition", "What is Macrinus's ultimate ambition?", ["To kill Emperors Geta and Caracalla.", "To use Lucius only to become popular.", "To conquer Rome."], 2, "What goes wrong with his plan?"],
    ["war", "How does Lucius stop the armies from starting a war?", ["Before killing Macrinus and Caracalla, he says he is Marcus Aurelius's son.", "After killing Acacius, he says he is Lucilla's son and heir.", "He kills Macrinus and reveals that he is Marcus Aurelius's grandson and part of the imperial bloodline."], 2, "Is it a good ending?"]
  ];
  const during = ["Who are Hanno and Lucius? What do they have in common?", "What happens in the first battle?", "Who are Lucilla and Acacius?", "What is Lucilla and Acacius's plan?", "Is Macrinus a good man?", "Why is the Colosseum important to the emperors?"];
  const sortItems = [["gladiators", "Gladiators", "roman"], ["emperors", "Emperors", "roman"], ["italy", "Italy", "roman"], ["colosseum", "Colosseum", "roman"], ["kings", "Kings", "inca"], ["machu-picchu", "Machu Picchu", "inca"], ["amazon", "Amazon Forest", "inca"], ["peru", "Peru", "inca"]];
  const defaults = () => ({ before: {}, sorted: {}, selected: "", sortOrder: [], during: [], after: {}, writing: "", name: "", teacher: "", orders: {}, wrong: {} });
  let state; try { state = { ...defaults(), ...JSON.parse(localStorage.getItem(key) || "{}") }; } catch { state = defaults(); }
  for (const field of ["before", "after", "sorted", "orders", "wrong"]) state[field] ||= {}; state.during ||= [];
  state.sortOrder = window.myeEnsureShuffledOrder(sortItems.map(([id]) => id), state.sortOrder);
  const save = () => localStorage.setItem(key, JSON.stringify(state));
  const order = (group, question) => { const id = `${group}-${question[0]}`; return state.orders[id] = window.myeEnsureShuffledOrder(question[2].map((_, index) => index), state.orders[id]); };
  function renderQuiz(target, items, group) { const host = document.querySelector(target), position = host.querySelector(".question-carousel")?.scrollLeft || 0; host.innerHTML = `<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">←</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">→</button></div></div><div class="question-carousel">${items.map((question, index) => { const answer = state[group][question[0]], correct = answer === question[3], wrong = state.wrong[`${group}-${question[0]}`] || []; return `<div class="question-slide"><p class="slide-number">Question ${index + 1} of ${items.length}</p><article class="question-card ${correct ? "is-correct" : ""}"><p class="question-text">${question[1]}</p><div class="answer-options">${order(group, question).map((item, display) => `<button class="answer-choice ${answer === item ? "selected" : ""} ${wrong.includes(item) ? "was-wrong" : ""}" data-group="${group}" data-id="${question[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65 + display)}</span>${question[2][item]}</button>`).join("")}</div><p class="question-feedback">${answer === undefined ? "" : correct ? `Correct. ${question[4]}` : (question[5]?.[answer] || "Not quite. Try another answer.")}</p></article></div>`; }).join("")}</div></div>`; host.querySelector(".question-carousel").scrollLeft = position; }
  const findItem = (id) => sortItems.find(([value]) => value === id);
  function renderSort() { document.querySelector("#empire-sort-bank").innerHTML = state.sortOrder.filter((id) => !state.sorted[id]).map((id) => `<button class="paris-sort-chip ${state.selected === id ? "is-selected" : ""}" draggable="true" type="button" data-sort-item="${id}">${findItem(id)[1]}</button>`).join("") || "<p>Every item has been placed.</p>"; ["roman", "inca"].forEach((zone) => { document.querySelector(`#${zone}-items`).innerHTML = state.sortOrder.filter((id) => state.sorted[id] === zone).map((id) => `<button type="button" data-return-item="${id}">${findItem(id)[1]}</button>`).join(""); }); document.querySelector("#empire-sort-feedback").textContent = Object.keys(state.sorted).length === sortItems.length ? "Excellent! Every item is in the correct empire." : `${Object.keys(state.sorted).length} / ${sortItems.length} items sorted`; }
  function place(id, zone) { if (findItem(id)?.[2] === zone) state.sorted[id] = zone; state.selected = ""; render(); }
  function render() { renderQuiz("#before-questions", before, "before"); renderQuiz("#after-questions", after, "after"); renderSort(); document.querySelector("#during-checklist").innerHTML = during.map((item, index) => `<button class="watch-item ${state.during.includes(index) ? "done" : ""}" data-during="${index}" type="button"><span>${state.during.includes(index) ? "✓" : "○"}</span>${item}</button>`).join(""); for (const [id, value] of [["student-writing", state.writing], ["student-name", state.name], ["teacher-name", state.teacher]]) document.getElementById(id).value = value; document.querySelector("#writing-feedback").textContent = state.writing.trim().length >= 50 ? "Writing task complete." : "Write at least 50 characters to complete this activity."; const quizDone = [["before", before], ["after", after]].reduce((sum, [group, questions]) => sum + questions.filter((question) => state[group][question[0]] === question[3]).length, 0), completed = quizDone + Object.keys(state.sorted).length + state.during.length + (state.writing.trim().length >= 50 ? 1 : 0); document.querySelector("#progress-label").textContent = `${completed} / ${totalActivities} complete`; document.querySelector("#progress-bar").style.width = `${completed / totalActivities * 100}%`; save(); }
  document.addEventListener("click", (event) => { const choice = event.target.closest("[data-group][data-answer]"); if (choice) { const group = choice.dataset.group, question = (group === "before" ? before : after).find((item) => item[0] === choice.dataset.id), answer = Number(choice.dataset.answer); if (state[group][choice.dataset.id] !== question[3]) { state[group][choice.dataset.id] = answer; if (answer !== question[3]) { const id = `${group}-${choice.dataset.id}`; state.wrong[id] = [...new Set([...(state.wrong[id] || []), answer])]; } } render(); return; } const chip = event.target.closest("[data-sort-item]"); if (chip) { state.selected = state.selected === chip.dataset.sortItem ? "" : chip.dataset.sortItem; renderSort(); return; } const zone = event.target.closest("[data-empire-zone]"); if (zone && state.selected) { place(state.selected, zone.dataset.empireZone); return; } const returned = event.target.closest("[data-return-item]"); if (returned) { delete state.sorted[returned.dataset.returnItem]; render(); return; } const watch = event.target.closest("[data-during]"); if (watch) { const index = Number(watch.dataset.during); state.during = state.during.includes(index) ? state.during.filter((value) => value !== index) : [...state.during, index]; render(); } });
  document.addEventListener("dragstart", (event) => { const chip = event.target.closest("[data-sort-item]"); if (chip) event.dataTransfer.setData("text/plain", chip.dataset.sortItem); }); document.querySelectorAll("[data-empire-zone]").forEach((zone) => { zone.addEventListener("dragover", (event) => event.preventDefault()); zone.addEventListener("drop", (event) => { event.preventDefault(); place(event.dataTransfer.getData("text/plain"), zone.dataset.empireZone); }); zone.addEventListener("keydown", (event) => { if ((event.key === "Enter" || event.key === " ") && state.selected) { event.preventDefault(); place(state.selected, zone.dataset.empireZone); } }); });
  for (const [id, field] of [["student-writing", "writing"], ["student-name", "name"], ["teacher-name", "teacher"]]) document.getElementById(id).addEventListener("input", (event) => { state[field] = event.target.value; render(); }); document.querySelector("#reset-lesson").addEventListener("click", () => { if (confirm("Reset lesson progress?")) { state = defaults(); state.sortOrder = window.myeEnsureShuffledOrder(sortItems.map(([id]) => id)); render(); } }); render();
})();
