const key = "mye-conclave-v1", totalActivities = 20;
const defaults = { before: {}, during: [], after: {}, writing: "", name: "", teacher: "", orders: {} };
let saved = {}; try { saved = JSON.parse(localStorage.getItem(key) || "{}"); } catch { localStorage.removeItem(key); } let state = { ...defaults, ...saved, orders: { ...(saved.orders || {}) } };
const before = [
  ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["After the Pope retires, a cardinal manages the ritual of electing a successor amid a dispute between powerful Church leaders.", "After the Pope dies unexpectedly, a cardinal manages the ancient ritual of electing a successor amid a dispute between powerful Church leaders.", "After the Pope dies, a cardinal independently organizes the conclave to defend his own position."], 1, "Get ready for a great plot."],
  ["papacy", "During his ________, the ________ focused on helping the poor.", ["church – king", "Pope – papacy", "papacy – Pope", "papal – Pope"], 2, "Who is the current Pope? Would you like to be the Pope?"],
  ["church", "_________ celebrates Christmas and Easter as important holidays.", ["Buddhism", "Spiritism", "The Catholic Church", "Taoism"], 2, "Are you Catholic?"],
  ["cardinal", "A _________ is a high-ranking leader in the Catholic Church who helps guide the Church and choose a new pope.", ["cardiac", "card", "cardinal", "carnival"], 2, "Is it an easy job?"],
  ["conclave", "A conclave is...", ["an online meeting in Rome to choose a new pope.", "a secret interreligious meeting to choose a new pope.", "a private meeting where Catholic cardinals choose a new pope after the previous one dies or resigns.", "a public meeting where Catholic people choose a new pope."], 2, "Do you remember the last conclave?"],
  ["vatican", "_________ is the smallest country in the world and the center of the Roman Catholic Church.", ["Italy", "Rome", "The Vatican", "Malta"], 2, "Have you ever been there?"],
  ["nun", "A nun is...", ["a woman who lives a religious life only at home.", "a boy who lives a religious life in a convent.", "a woman who has chosen a religious life, often in a convent.", "a woman who serves only the Pope in a convent."], 2, "Do you understand their motivation?"]
];
const after = [
  ["task", "What is Cardinal-Dean Thomas Lawrence's task?", ["Investigate Aldo Bellini.", "Organize the conclave to elect the next cardinal.", "Organize the conclave to elect the next Pope."], 2, "Is it an easy task?"],
  ["bellini", "How is Bellini different from Tremblay and Adeyemi?", ["They are all extremely liberal, like Tedesco.", "Bellini is more conservative, while the others are more liberal.", "Bellini is more liberal, while Tremblay and Adeyemi are more conservative."], 2, "Who was the best candidate, in your opinion?"],
  ["adeyemi", "Why does Adeyemi lose all his votes?", ["He does not want the papacy.", "He is exposed for bribing the cardinals.", "A sister exposes an affair they had in the past."], 2, "Was it a fair decision?"],
  ["benitez", "Who is Cardinal Vincent Benitez?", ["The Archbishop of Kabul.", "A Mexican cardinal.", "A cardinal created in secret by the Pope.", "All the other options."], 3, "Is he a good person?"],
  ["switzerland", "Why did Benitez travel to Switzerland?", ["To fight against Muslims after a suicide bombing.", "To become the next Pope.", "For a medical procedure."], 2, "What was the procedure?"],
  ["pope", "Who is elected the new Pope?", ["Tedesco.", "Lawrence.", "Benitez."], 2, "Would you have voted for him?"]
];
const during = ["How does the movie start, and how does that influence the story?", "Who is Cardinal Lawrence?", "What are Lawrence's responsibilities?", "Who are the strongest candidates for the position?", "Are the candidates similar? Who would you vote for?", "What important decision does Lawrence make at the end?"];
const save = () => localStorage.setItem(key, JSON.stringify(state)), count = (object) => Object.keys(object).length, writingComplete = () => state.writing.trim().length >= 50;
const progress = () => count(state.before) + state.during.length + count(state.after) + (writingComplete() ? 1 : 0);
function order(group, id, options) { const k = `${group}-${id}`; if (!state.orders[k]) { state.orders[k] = options.map((_, i) => i).sort(() => Math.random() - .5); save(); } return state.orders[k]; }
function renderQuiz(target, items, group) { const host = document.querySelector(target), position = host.querySelector(".question-carousel")?.scrollLeft || 0; host.innerHTML = `<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">&#8592;</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">&#8594;</button></div></div><div class="question-carousel">${items.map((q, i) => { const answer = state[group][q[0]], correct = answer === q[3]; return `<div class="question-slide"><p class="slide-number">Question ${i + 1} of ${items.length}</p><article class="question-card ${correct ? "is-correct" : ""}"><p class="question-text">${q[1]}</p><div class="answer-options">${order(group, q[0], q[2]).map((item, display) => `<button class="answer-choice ${answer === item ? "selected" : ""}" data-group="${group}" data-id="${q[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65 + display)}</span>${q[2][item]}</button>`).join("")}</div><p class="question-feedback">${answer === undefined ? "" : correct ? `Correct. ${q[4]}` : "Not quite. Try another answer."}</p></article></div>`; }).join("")}</div></div>`; host.querySelector(".question-carousel").scrollLeft = position; }
function render() { renderQuiz("#before-questions", before, "before"); renderQuiz("#after-questions", after, "after"); document.querySelector("#during-checklist").innerHTML = during.map((item, i) => `<button class="watch-item ${state.during.includes(i) ? "done" : ""}" data-during="${i}" type="button"><span>${state.during.includes(i) ? "✓" : "○"}</span>${item}</button>`).join(""); document.querySelector("#student-writing").value = state.writing; document.querySelector("#student-name").value = state.name; document.querySelector("#teacher-name").value = state.teacher; document.querySelector("#writing-feedback").textContent = writingComplete() ? "Writing task complete." : "Write at least 50 characters to complete this activity."; const completed = progress(); document.querySelector("#progress-label").textContent = `${completed} / ${totalActivities} complete`; document.querySelector("#progress-bar").style.width = `${completed / totalActivities * 100}%`; }
document.addEventListener("click", (event) => { const choice = event.target.closest("[data-group]"); if (choice) { state[choice.dataset.group][choice.dataset.id] = +choice.dataset.answer; save(); render(); return; } const watch = event.target.closest("[data-during]"); if (watch) { const i = +watch.dataset.during; state.during = state.during.includes(i) ? state.during.filter((value) => value !== i) : [...state.during, i]; save(); render(); return; } const nav = event.target.closest("[data-nav]"); if (nav) { const carousel = nav.closest(".question-carousel-shell").querySelector(".question-carousel"); carousel.scrollBy({ left: carousel.clientWidth * (nav.dataset.nav === "next" ? 1 : -1), behavior: "smooth" }); } });
["student-writing", "student-name", "teacher-name"].forEach((id) => document.querySelector(`#${id}`).addEventListener("input", (event) => { state[id === "student-writing" ? "writing" : id === "student-name" ? "name" : "teacher"] = event.target.value; save(); render(); })); document.querySelector("#reset-lesson").addEventListener("click", () => { if (confirm("Reset lesson progress?")) { state = { ...defaults, before: {}, during: [], after: {}, orders: {} }; save(); render(); } }); render();
