const key = "mye-the-batman-v1", totalActivities = 31;
const defaults = { before: {}, sorted: {}, selected: "", sortOrder: [], during: [], after: {}, writing: "", name: "", teacher: "", orders: {} };
let saved = {}; try { saved = JSON.parse(localStorage.getItem(key) || "{}"); } catch { localStorage.removeItem(key); } let state = { ...defaults, ...saved, sorted: { ...(saved.sorted || {}) }, orders: { ...(saved.orders || {}) } };
const before = [
  ["plot", "Based on the trailer and your knowledge, which plot is correct?", ["Batman and Robin investigate a killer targeting Gotham politicians and the Wayne family.", "Batman investigates a sadistic killer targeting Gotham politicians, the city’s corruption, and his own family’s involvement.", "Batman investigates a killer targeting Gotham’s superheroes and fights his own friends."], 1, "Get ready for some dark and exciting action scenes!"],
  ["bat", "A __________ is a small nocturnal animal with wings that uses echolocation.", ["penguin", "rat", "bat", "cat"], 2, "Are you afraid of bats?"],
  ["riddles", "___________ entertain children while improving their problem-solving skills.", ["Answers", "Questions", "Riddles", "Comments"], 2, "What has keys but cannot open locks?"],
  ["bomb", "The firefighters evacuated the building after discovering an old __________.", ["bunker", "puzzle", "bomb", "feline"], 2, "A bomb is a device that can explode and cause harm."],
  ["vigilante", "A vigilante is...", ["always a man who believes the police punish criminals appropriately.", "a person who supports the mayor and the legal system.", "a person who believes the legal system is ineffective and personally punishes suspected criminals.", "a person who protests against the police every day."], 2, "Have you heard any stories about vigilantes?"],
  ["nightclub", "A _____________ is a place people visit late at night to dance, listen to music, and socialize.", ["clubnight", "dance night", "nightclub", "fight club"], 2, "Do you enjoy going to nightclubs?"],
  ["seawall", "The town built a ___________ to stop rising tides from flooding the shore.", ["seal", "great wall", "sea wall", "harbor"], 2, "A sea wall protects coastal areas from flooding."],
  ["vengeance", "People who want ___________ often want another person to feel the pain they caused.", ["signals", "relevance", "vengeance", "debates"], 2, "Is vengeance necessary?"]
];
const after = [
  ["bruce", "Who is Bruce Wayne?", ["Thomas Wayne’s youngest son and Gotham’s future mayor.", "A billionaire who abandoned his wife to help the police.", "A billionaire who spent the last two years fighting criminals in Gotham."], 2, "If you were a billionaire, would you do that?"],
  ["catwoman", "Who is Catwoman?", ["Selina, Bruce’s girlfriend and IT assistant.", "Annika, a dancer at Penguin’s nightclub.", "Selina, who is also Falcone’s daughter."], 2, "Did you like her?"],
  ["penguin", "Why does Batman chase Penguin?", ["The Riddler clearly identifies Oz as El Rata Alada.", "Batman believes Falcone is in Penguin’s car.", "Batman and Gordon believe Penguin is the rat."], 2, "Were they right?"],
  ["alfred", "Why does Alfred almost die?", ["The Riddler wants revenge for Thomas Wayne’s death.", "The Riddler explodes Alfred’s house.", "Alfred opens a package from the Riddler addressed to Bruce."], 2, "Why was the Riddler trying to kill Bruce?"],
  ["falcone", "Why is Falcone arrested?", ["For killing Thomas Wayne.", "For abandoning Selina.", "For killing Annika."], 2, "Does he go to jail?"],
  ["final", "What is the Riddler’s final plan?", ["Convince Batman to help kill Bruce Wayne and Gordon.", "Kill the new mayor and explode the stadium.", "Destroy Gotham Harbor’s sea walls and flood the city on election night."], 2, "Does it happen?"]
];
const during = ["Who is Bruce Wayne? Does he come from a normal family?", "Who are Alfred and Lieutenant Gordon?", "How are Annika and Selina involved in the story?", "Are Annika and Selina important to Bruce?", "Who are the Riddler, Falcone, and Oz?", "What are the main problems in Gotham City?"];
const sortItems = [["clean", "Clean", "vienna"], ["safe", "Safe", "vienna"], ["amusing", "Amusing", "vienna"], ["green", "Green", "vienna"], ["peaceful", "Peaceful", "vienna"], ["gloomy", "Gloomy", "gotham"], ["dark", "Dark", "gotham"], ["dangerous", "Dangerous", "gotham"], ["chaotic", "Chaotic", "gotham"], ["bleak", "Bleak", "gotham"]];
const save = () => localStorage.setItem(key, JSON.stringify(state)), count = (object) => Object.keys(object).length, writingComplete = () => state.writing.trim().length >= 50;
if (!state.sortOrder.length) { state.sortOrder = sortItems.map(([id]) => id).sort(() => Math.random() - .5); save(); }
const progress = () => count(state.before) + count(state.sorted) + state.during.length + count(state.after) + (writingComplete() ? 1 : 0);
function order(group, id, options) { const k = `${group}-${id}`; if (!state.orders[k]) { state.orders[k] = options.map((_, i) => i).sort(() => Math.random() - .5); save(); } return state.orders[k]; }
function renderQuiz(target, items, group) { const host = document.querySelector(target), position = host.querySelector(".question-carousel")?.scrollLeft || 0; host.innerHTML = `<div class="question-carousel-shell"><div class="question-carousel-toolbar"><span>Questions</span><div><button class="question-carousel-button" data-nav="previous" type="button" aria-label="Previous question">&#8592;</button><button class="question-carousel-button" data-nav="next" type="button" aria-label="Next question">&#8594;</button></div></div><div class="question-carousel">${items.map((q, i) => { const answer = state[group][q[0]], correct = answer === q[3]; return `<div class="question-slide"><p class="slide-number">Question ${i + 1} of ${items.length}</p><article class="question-card ${correct ? "is-correct" : ""}"><p class="question-text">${q[1]}</p><div class="answer-options">${order(group, q[0], q[2]).map((item, display) => `<button class="answer-choice ${answer === item ? "selected" : ""}" data-group="${group}" data-id="${q[0]}" data-answer="${item}" type="button"><span>${String.fromCharCode(65 + display)}</span>${q[2][item]}</button>`).join("")}</div><p class="question-feedback">${answer === undefined ? "" : correct ? `Correct. ${q[4]}` : "Not quite. Try another answer."}</p></article></div>`; }).join("")}</div></div>`; host.querySelector(".question-carousel").scrollLeft = position; }
function renderSort() { const item = (id) => sortItems.find(([value]) => value === id); document.querySelector("#city-sort-bank").innerHTML = state.sortOrder.filter((id) => !state.sorted[id]).map((id) => `<button class="paris-sort-chip ${state.selected === id ? "is-selected" : ""}" draggable="true" type="button" data-sort-item="${id}">${item(id)[1]}</button>`).join("") || "<p>Every adjective has been placed.</p>"; ["vienna", "gotham"].forEach((zone) => { document.querySelector(`#${zone}-items`).innerHTML = state.sortOrder.filter((id) => state.sorted[id] === zone).map((id) => `<button type="button" data-return-item="${id}">${item(id)[1]}</button>`).join(""); }); document.querySelector("#city-sort-feedback").textContent = count(state.sorted) === sortItems.length ? "Excellent. Every adjective is in the correct city." : `${count(state.sorted)} / ${sortItems.length} adjectives sorted`; }
function place(id, zone) { if (sortItems.find(([value]) => value === id)?.[2] === zone) state.sorted[id] = zone; state.selected = ""; save(); render(); }
function render() { renderQuiz("#before-questions", before, "before"); renderQuiz("#after-questions", after, "after"); renderSort(); document.querySelector("#during-checklist").innerHTML = during.map((item, i) => `<button class="watch-item ${state.during.includes(i) ? "done" : ""}" data-during="${i}" type="button"><span>${state.during.includes(i) ? "✓" : "○"}</span>${item}</button>`).join(""); document.querySelector("#student-writing").value = state.writing; document.querySelector("#student-name").value = state.name; document.querySelector("#teacher-name").value = state.teacher; document.querySelector("#writing-feedback").textContent = writingComplete() ? "Writing task complete." : "Write at least 50 characters to complete this activity."; const completed = progress(); document.querySelector("#progress-label").textContent = `${completed} / ${totalActivities} complete`; document.querySelector("#progress-bar").style.width = `${completed / totalActivities * 100}%`; }
document.addEventListener("click", (event) => { const choice = event.target.closest("[data-group]"); if (choice) { state[choice.dataset.group][choice.dataset.id] = +choice.dataset.answer; save(); render(); return; } const chip = event.target.closest("[data-sort-item]"); if (chip) { state.selected = state.selected === chip.dataset.sortItem ? "" : chip.dataset.sortItem; save(); render(); return; } const zone = event.target.closest("[data-city-zone]"); if (zone && state.selected) { place(state.selected, zone.dataset.cityZone); return; } const returned = event.target.closest("[data-return-item]"); if (returned) { delete state.sorted[returned.dataset.returnItem]; save(); render(); return; } const watch = event.target.closest("[data-during]"); if (watch) { const i = +watch.dataset.during; state.during = state.during.includes(i) ? state.during.filter((value) => value !== i) : [...state.during, i]; save(); render(); return; } const nav = event.target.closest("[data-nav]"); if (nav) { const carousel = nav.closest(".question-carousel-shell").querySelector(".question-carousel"); carousel.scrollBy({ left: carousel.clientWidth * (nav.dataset.nav === "next" ? 1 : -1), behavior: "smooth" }); } });
document.addEventListener("dragstart", (event) => { const chip = event.target.closest("[data-sort-item]"); if (chip) event.dataTransfer.setData("text/plain", chip.dataset.sortItem); }); document.querySelectorAll("[data-city-zone]").forEach((zone) => { zone.addEventListener("dragover", (event) => event.preventDefault()); zone.addEventListener("drop", (event) => { event.preventDefault(); place(event.dataTransfer.getData("text/plain"), zone.dataset.cityZone); }); zone.addEventListener("keydown", (event) => { if ((event.key === "Enter" || event.key === " ") && state.selected) { event.preventDefault(); place(state.selected, zone.dataset.cityZone); } }); });
["student-writing", "student-name", "teacher-name"].forEach((id) => document.querySelector(`#${id}`).addEventListener("input", (event) => { state[id === "student-writing" ? "writing" : id === "student-name" ? "name" : "teacher"] = event.target.value; save(); render(); })); document.querySelector("#reset-lesson").addEventListener("click", () => { if (confirm("Reset lesson progress?")) { state = { ...defaults, before: {}, sorted: {}, selected: "", sortOrder: sortItems.map(([id]) => id).sort(() => Math.random() - .5), during: [], after: {}, orders: {} }; save(); render(); } }); render();
